name: Validar Recursos

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'bloques-de-funcion/**'
      - 'tipos-de-datos/**'
      - 'bloques-de-organizacion/**'
      - 'hmi/**'
      - 'plantillas-de-proyecto/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Verificar estructura de subcarpetas
        run: bash scripts/validate-resources.sh
